### ISSUE TITLE
HTTP Error 401

### ISSUE THREAD

**Issue by bessakhi** [ManageIQ/ansible-manageiq-automate#4]
TASK [syncrou.manageiq-automate : Initialize the Workspace] ********************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "HTTP Error 401: Unauthorized"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

**Comment by gtanzillo** [comment]
Closing due to lack of information
